name: Build and Test

on:
  pull_request:
  workflow_dispatch:

env:
  CORRETTO_VERSION: 17.0.6.10.1
  JDK_FILE_PATH: /tmp/downloads/Corretto.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '17'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Create MySQL Container
        run: |
          docker run \
              -e MYSQL_ROOT_PASSWORD=password \
              -e MYSQL_USER=user \
              -e MYSQL_PASSWORD=password \
              -e MYSQL_DATABASE=db \
              -e TZ=Asia/Tokyo \
              --name test \
              -v ~/mysql:/var/lib/mysql \
              -p 127.0.0.1:3306:3306 \
              --platform=linux/x86_64 \
              -d mysql:8.0.32 \

      - name: Db Migrate
        run: |
          echo -n "Waiting for mysql ready: "
          while ! docker exec test mysqladmin -uroot -ppassword --host "127.0.0.1" ping --silent &> /dev/null; do
            printf "." && sleep 1
          done
          echo ok

          ./gradlew flywayMigrate

      - name: build and test
        run: |
          ./gradlew build
